In [6]:
import pandas as pd

# Load the dataset
file_path = "cleaned_german_data.xlsx"
df = pd.read_excel(file_path)

# Display basic information about the dataset
df.info(), df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    1000 non-null   object
 1   Col2    1000 non-null   int64
 2   Col3    1000 non-null   object
 3   Col4    1000 non-null   object
 4   Col5    1000 non-null   int64
 5   Col6    1000 non-null   object
 6   Col7    1000 non-null   object
 7   Col8    1000 non-null   int64
 8   Col9    1000 non-null   object
 9   Col11   1000 non-null   int64
 10  Col12   1000 non-null   object
 11  Col13   1000 non-null   int64
 12  Col14   1000 non-null   object
 13  Col15   1000 non-null   object
 14  Col16   1000 non-null   int64
 15  Col18   1000 non-null   int64
 16  Col20   1000 non-null   object
 17  Col21   1000 non-null   int64
dtypes: int64(8), object(10)
memory usage: 140.8+ KB

(None,
   Col1  Col2 Col3 Col4  Col5 Col6 Col7  Col8 Col9  Col11 Col12  Col13 Col14  \
 0  A11     6  A34  A43  1169  A65  A75     4  A93      4  A121     67  A143
 1  A12    48  A32  A43  5951  A61  A73     2  A92      2  A121     22  A143
 2  A14    12  A34  A46  2096  A61  A74     2  A93      3  A121     49  A143
 3  A11    42  A32  A42  7882  A61  A74     2  A93      4  A122     45  A143
 4  A11    24  A33  A40  4870  A61  A73     3  A93      4  A124     53  A143

   Col15  Col16  Col18 Col20  Col21
 0  A152      2      1  A201      1
 1  A152      1      1  A201      2
 2  A152      1      2  A201      1
 3  A153      1      2  A201      1
 4  A153      2      2  A201      2  )

In [7]:
# Rename the columns
column_names = {
    "Col1": "Status_of_existing_checking_account",
    "Col2": "Duration_in_month",
    "Col3": "Credit_history",
    "Col4": "Purpose",
    "Col5": "Credit_amount",
    "Col6": "Savings_account_bonds",
    "Col7": "Present_employment_since",
    "Col8": "Installment_rate",
    "Col9": "Personal_status_and_sex",
    "Col11": "Other_debtors_guarantors",
    "Col12": "Present_residence_since",
    "Col13": "Age_in_years",
    "Col14": "Other_installment_plans",
    "Col15": "Housing",
    "Col16": "Number_of_existing_credits",
    "Col18": "Job",
    "Col20": "Number_of_people_liable",
    "Col21": "Credit_risk"
}

df.rename(columns=column_names, inplace=True)

# Display the first few rows after renaming
df.head()

,Status_of_existing_checking_account,Duration_in_month,Credit_history,Purpose,Credit_amount,Savings_account_bonds,Present_employment_since,Installment_rate,Personal_status_and_sex,Other_debtors_guarantors,Present_residence_since,Age_in_years,Other_installment_plans,Housing,Number_of_existing_credits,Job,Number_of_people_liable,Credit_risk
0,A11,6,A34,A43,1169,A65,A75,4,A93,4,A121,67,A143,A152,2,1,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,2,A121,22,A143,A152,1,1,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,3,A121,49,A143,A152,1,2,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,4,A122,45,A143,A153,1,2,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,4,A124,53,A143,A153,2,2,A201,2

In [8]:
# Define mappings for categorical variables based on German Credit Dataset documentation

checking_account_status_map = {
    "A11": "No checking account",
    "A12": "Less than 200 DM",
    "A13": "More than 200 DM",
    "A14": "No checking account (in another bank)"
}

credit_history_map = {
    "A30": "No credit taken",
    "A31": "All credits paid duly",
    "A32": "Existing credit paid duly",
    "A33": "Delay in past payments",
    "A34": "Critical account (other credits existing)"
}

purpose_map = {
    "A40": "Car (new)",
    "A41": "Car (used)",
    "A42": "Furniture/equipment",
    "A43": "Radio/television",
    "A44": "Domestic appliances",
    "A45": "Repairs",
    "A46": "Education",
    "A47": "Vacation",
    "A48": "Retraining",
    "A49": "Business",
    "A410": "Other"
}

savings_account_map = {
    "A61": "No savings account",
    "A62": "Less than 100 DM",
    "A63": "100 to 500 DM",
    "A64": "500 to 1000 DM",
    "A65": "More than 1000 DM"
}

employment_map = {
    "A71": "Unemployed",
    "A72": "Less than 1 year",
    "A73": "1 to 4 years",
    "A74": "4 to 7 years",
    "A75": "More than 7 years"
}

personal_status_map = {
    "A91": "Male: divorced/separated",
    "A92": "Female: divorced/separated/married",
    "A93": "Male: single",
    "A94": "Male: married/widowed",
    "A95": "Female: single"
}

other_debtors_map = {
    "A101": "None",
    "A102": "Co-applicant",
    "A103": "Guarantor"
}

residence_map = {
    "A121": "Less than 1 year",
    "A122": "1 to 2 years",
    "A123": "2 to 3 years",
    "A124": "More than 3 years"
}

installment_plan_map = {
    "A141": "Bank",
    "A142": "Stores",
    "A143": "None"
}

housing_map = {
    "A151": "Own",
    "A152": "Rent",
    "A153": "For free"
}

job_map = {
    1: "Unskilled",
    2: "Unskilled (resident)",
    3: "Skilled",
    4: "Highly qualified"
}

liable_people_map = {
    "A201": "One",
    "A202": "Two or more"
}

credit_risk_map = {
    1: "Good credit risk",
    2: "Bad credit risk"
}

# Apply mappings to categorical columns
df.replace({
    "Status_of_existing_checking_account": checking_account_status_map,
    "Credit_history": credit_history_map,
    "Purpose": purpose_map,
    "Savings_account_bonds": savings_account_map,
    "Present_employment_since": employment_map,
    "Personal_status_and_sex": personal_status_map,
    "Other_debtors_guarantors": other_debtors_map,
    "Present_residence_since": residence_map,
    "Other_installment_plans": installment_plan_map,
    "Housing": housing_map,
    "Job": job_map,
    "Number_of_people_liable": liable_people_map,
    "Credit_risk": credit_risk_map
}, inplace=True)

# Display the first few rows after replacing categorical values
df.head()

,Status_of_existing_checking_account,Duration_in_month,Credit_history,Purpose,Credit_amount,Savings_account_bonds,Present_employment_since,Installment_rate,Personal_status_and_sex,Other_debtors_guarantors,Present_residence_since,Age_in_years,Other_installment_plans,Housing,Number_of_existing_credits,Job,Number_of_people_liable,Credit_risk
0,No checking account,6,Critical account (other credits existing),Radio/television,1169,More than 1000 DM,More than 7 years,4,Male: single,4,Less than 1 year,67,None,Rent,2,Unskilled,One,Good credit risk
1,Less than 200 DM,48,Existing credit paid duly,Radio/television,5951,No savings account,1 to 4 years,2,Female: divorced/separated/married,2,Less than 1 year,22,None,Rent,1,Unskilled,One,Bad credit risk
2,No checking account (in another bank),12,Critical account (other credits existing),Education,2096,No savings account,4 to 7 years,2,Male: single,3,Less than 1 year,49,None,Rent,1,Unskilled (resident),One,Good credit risk
3,No checking account,42,Existing credit paid duly,Furniture/equipment,7882,No savings account,4 to 7 years,2,Male: single,4,1 to 2 years,45,None,For free,1,Unskilled (resident),One,Good credit risk
4,No checking account,24,Delay in past payments,Car (new),4870,No savings account,1 to 4 years,3,Male: single,4,More than 3 years,53,None,For free,2,Unskilled (resident),One,Bad credit risk

In [9]:
df.to_excel("cleaned_german_data_modified.xlsx", index=False)